### ISSUE TITLE
Automatic documentations and schemas 

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restapi-template#2]
We should check swagger.

A useful way to start could be checking out the marshmallow people's work:
https://github.com/marshmallow-code/apispec

**Comment by pdonorio** [comment]
A good repository for our case:
https://github.com/rantav/flask-restful-swagger

Other integrations are available [here](http://swagger.io/open-source-integrations/)

**Comment by pdonorio** [comment]
Also an agnostic tool for unittest based on swagger description:
https://github.com/apiaryio/dredd

**Comment by pdonorio** [comment]
This is doing pretty good so far in the http-api-base.
Things to be fixed:

- [x] before flask start listening to requests, [iter on flask mapping](https://github.com/gangverk/flask-swagger/blob/master/flask_swagger.py#L168) and remove mappings that do not appear in swagger

- [x] if flask is launched in testing mode, ignore the `publish: false` statements

- [x] convert `/api/blablabla/schema` into `/api/schemas/blablabla`

**Comment by mdantonio** [comment]
- [ ] Avoid parameters duplication between POST and PUT (with formData parameters the $ref solution seems to be not applicable)

**Comment by pdonorio** [comment]
> Avoid parameters duplication between POST and PUT

I didn't understand what that means :)

**Comment by mdantonio** [comment]
With in:body parameters it is possibile to define a schema in the _definitions_ section and than set a reference into POST and PUT endpoints with $ref

With in:formData parameters this mechanism doesn't work, so parameters have to be duplicated into the _parameters_ section of each method (POST and PUT in particular)

**Comment by pdonorio** [comment]
Tomorrow give me more hints on how to solve this problem.

**Comment by pdonorio** [comment]
Closed with 8ba30fad2de17cce35e2eaa87e3449c07f0d3ea8
